language: python

matrix:
  fast_finish: true
  include:
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="2.7"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.6"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n conda_env python=$PYTHON_VERSION
  - conda activate conda_env
  - conda install matplotlib networkx nose2 pip setuptools

script:
  - conda activate conda_env
  - python setup.py install
  - nose2 -v -s pygraphml
